In [3]:
import torch
from torch import nn,optim
from torch.utils.data import DataLoader,Dataset

In [ ]:
x1 = torch.tensor([])

In [5]:
torch.manual_seed(1)

In [6]:
model = nn.Linear(2,1)

In [7]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.3643, -0.3121]], requires_grad=True),
 Parameter containing:
 tensor([-0.1371], requires_grad=True)]

In [8]:
X = torch.tensor([[1.,3.]])

In [10]:
y_hat     = model(X)
y_hat

tensor([[-0.7090]], grad_fn=<AddmmBackward0>)

In [11]:
class LR(nn.Module):
    def __init__(self, in_features, out_features):
        super(LR,self).__init__()
        self.linear = nn.Linear(in_features,out_features)
    def forward(self,X):
        return self.linear(X)

In [29]:
class Data2D(Dataset):
    def __init__(self):
        self.X = torch.zeros((20,2))
        self.X[:,0] = torch.linspace(-1., 1., 20)
        self.X[:,1] = torch.linspace(-1., 1., 20)
        self.w = torch.tensor([[0.1],[2.]])
        self.b = 2.
        self.f = torch.mm(self.X,self.w) + self.b
        self.y = self.f + 0.1 * torch.randn((self.X.shape[0],1))
        self.len = self.X.shape[0]

    def __getitem__(self, index):
        return self.X[index] , self.y[index]
    def __len__(self):
        return self.len

In [30]:
train_set = Data2D()
citerion = nn.MSELoss()
train_loader = DataLoader(train_set,batch_size=2)

In [31]:
model = LR(in_features=2,out_features=1)
optimizer = optim.SGD(model.parameters(),lr=0.01)

In [32]:
for epoch in range(10):
    for X_batch , y_batch in train_loader:
        y_hat = model(X_batch)
        loss = citerion(y_hat, y_batch)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        print(loss)

tensor(1.9932, grad_fn=<MseLossBackward0>)
tensor(0.5856, grad_fn=<MseLossBackward0>)
tensor(0.0284, grad_fn=<MseLossBackward0>)
tensor(0.5496, grad_fn=<MseLossBackward0>)
tensor(2.1351, grad_fn=<MseLossBackward0>)
tensor(3.8429, grad_fn=<MseLossBackward0>)
tensor(7.1555, grad_fn=<MseLossBackward0>)
tensor(10.5326, grad_fn=<MseLossBackward0>)
tensor(15.5510, grad_fn=<MseLossBackward0>)
tensor(18.6699, grad_fn=<MseLossBackward0>)
tensor(1.7066, grad_fn=<MseLossBackward0>)
tensor(0.5731, grad_fn=<MseLossBackward0>)
tensor(0.0179, grad_fn=<MseLossBackward0>)
tensor(0.3120, grad_fn=<MseLossBackward0>)
tensor(1.4079, grad_fn=<MseLossBackward0>)
tensor(2.5480, grad_fn=<MseLossBackward0>)
tensor(4.9441, grad_fn=<MseLossBackward0>)
tensor(7.3508, grad_fn=<MseLossBackward0>)
tensor(11.1188, grad_fn=<MseLossBackward0>)
tensor(13.3211, grad_fn=<MseLossBackward0>)
tensor(1.4348, grad_fn=<MseLossBackward0>)
tensor(0.5387, grad_fn=<MseLossBackward0>)
tensor(0.0200, grad_fn=<MseLossBackward0>)
tensor